version: 2

jobs:
  build:
    docker:
      - image: "circleci/node:10.15.2-browsers-legacy@sha256:41d19ea0bdcd8be6675223645cfafee2c1353f412f8f843292b251ba3541ce1e"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install && npm run flow-install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
