version: 2

jobs:
  build:
    docker:
      - image: "circleci/node:10.19.0-browsers-legacy@sha256:4590bb91216efa8bed5c1bc13edc68883f0384053a57a60a8fcf03e4bc42bf98"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
