/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.iproto.BlockMeta');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iproto.BlockMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iproto.BlockMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.iproto.BlockMeta.displayName = 'proto.iproto.BlockMeta';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iproto.BlockMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.iproto.BlockMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iproto.BlockMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iproto.BlockMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
    hash: jspb.Message.getFieldWithDefault(msg, 1, ""),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0),
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0),
    numactions: jspb.Message.getFieldWithDefault(msg, 4, 0),
    produceraddress: jspb.Message.getFieldWithDefault(msg, 5, ""),
    transferamount: jspb.Message.getFieldWithDefault(msg, 6, ""),
    txroot: jspb.Message.getFieldWithDefault(msg, 7, ""),
    receiptroot: jspb.Message.getFieldWithDefault(msg, 8, ""),
    deltastatedigest: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iproto.BlockMeta}
 */
proto.iproto.BlockMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iproto.BlockMeta;
  return proto.iproto.BlockMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iproto.BlockMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iproto.BlockMeta}
 */
proto.iproto.BlockMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setHeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumactions(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProduceraddress(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransferamount(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxroot(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceiptroot(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeltastatedigest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iproto.BlockMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iproto.BlockMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iproto.BlockMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iproto.BlockMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getNumactions();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getProduceraddress();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTransferamount();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTxroot();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getReceiptroot();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDeltastatedigest();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string hash = 1;
 * @return {string}
 */
proto.iproto.BlockMeta.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.iproto.BlockMeta.prototype.setHash = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 height = 2;
 * @return {number}
 */
proto.iproto.BlockMeta.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.iproto.BlockMeta.prototype.setHeight = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 timestamp = 3;
 * @return {number}
 */
proto.iproto.BlockMeta.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.iproto.BlockMeta.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 numActions = 4;
 * @return {number}
 */
proto.iproto.BlockMeta.prototype.getNumactions = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.iproto.BlockMeta.prototype.setNumactions = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string producerAddress = 5;
 * @return {string}
 */
proto.iproto.BlockMeta.prototype.getProduceraddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.iproto.BlockMeta.prototype.setProduceraddress = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string transferAmount = 6;
 * @return {string}
 */
proto.iproto.BlockMeta.prototype.getTransferamount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.iproto.BlockMeta.prototype.setTransferamount = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string txRoot = 7;
 * @return {string}
 */
proto.iproto.BlockMeta.prototype.getTxroot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.iproto.BlockMeta.prototype.setTxroot = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string receiptRoot = 8;
 * @return {string}
 */
proto.iproto.BlockMeta.prototype.getReceiptroot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.iproto.BlockMeta.prototype.setReceiptroot = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string deltaStateDigest = 9;
 * @return {string}
 */
proto.iproto.BlockMeta.prototype.getDeltastatedigest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.iproto.BlockMeta.prototype.setDeltastatedigest = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


