/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.iproto.BlockFooterPb');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.iproto.EndorsementSet');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iproto.BlockFooterPb = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iproto.BlockFooterPb, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.iproto.BlockFooterPb.displayName = 'proto.iproto.BlockFooterPb';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iproto.BlockFooterPb.prototype.toObject = function(opt_includeInstance) {
  return proto.iproto.BlockFooterPb.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iproto.BlockFooterPb} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iproto.BlockFooterPb.toObject = function(includeInstance, msg) {
  var f, obj = {
    committimestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    endorsements: (f = msg.getEndorsements()) && proto.iproto.EndorsementSet.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iproto.BlockFooterPb}
 */
proto.iproto.BlockFooterPb.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iproto.BlockFooterPb;
  return proto.iproto.BlockFooterPb.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iproto.BlockFooterPb} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iproto.BlockFooterPb}
 */
proto.iproto.BlockFooterPb.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCommittimestamp(value);
      break;
    case 2:
      var value = new proto.iproto.EndorsementSet;
      reader.readMessage(value,proto.iproto.EndorsementSet.deserializeBinaryFromReader);
      msg.setEndorsements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iproto.BlockFooterPb.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iproto.BlockFooterPb.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iproto.BlockFooterPb} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iproto.BlockFooterPb.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommittimestamp();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getEndorsements();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.iproto.EndorsementSet.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 CommitTimestamp = 1;
 * @return {number}
 */
proto.iproto.BlockFooterPb.prototype.getCommittimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.iproto.BlockFooterPb.prototype.setCommittimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional EndorsementSet endorsements = 2;
 * @return {?proto.iproto.EndorsementSet}
 */
proto.iproto.BlockFooterPb.prototype.getEndorsements = function() {
  return /** @type{?proto.iproto.EndorsementSet} */ (
    jspb.Message.getWrapperField(this, proto.iproto.EndorsementSet, 2));
};


/** @param {?proto.iproto.EndorsementSet|undefined} value */
proto.iproto.BlockFooterPb.prototype.setEndorsements = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.iproto.BlockFooterPb.prototype.clearEndorsements = function() {
  this.setEndorsements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.iproto.BlockFooterPb.prototype.hasEndorsements = function() {
  return jspb.Message.getField(this, 2) != null;
};


