/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.iotexapi.GetActionsRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.iotexapi.GetActionByHashRequest');
goog.require('proto.iotexapi.GetActionsByBlockRequest');
goog.require('proto.iotexapi.GetActionsByIndexRequest');
goog.require('proto.iotexapi.GetUnconfirmedActionsByAddressRequest');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iotexapi.GetActionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.iotexapi.GetActionsRequest.oneofGroups_);
};
goog.inherits(proto.iotexapi.GetActionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.iotexapi.GetActionsRequest.displayName = 'proto.iotexapi.GetActionsRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.iotexapi.GetActionsRequest.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.iotexapi.GetActionsRequest.LookupCase = {
  LOOKUP_NOT_SET: 0,
  BYINDEX: 1,
  BYHASH: 2,
  BYADDR: 3,
  UNCONFIRMEDBYADDR: 4,
  BYBLK: 5
};

/**
 * @return {proto.iotexapi.GetActionsRequest.LookupCase}
 */
proto.iotexapi.GetActionsRequest.prototype.getLookupCase = function() {
  return /** @type {proto.iotexapi.GetActionsRequest.LookupCase} */(jspb.Message.computeOneofCase(this, proto.iotexapi.GetActionsRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iotexapi.GetActionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.iotexapi.GetActionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iotexapi.GetActionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotexapi.GetActionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    byindex: (f = msg.getByindex()) && proto.iotexapi.GetActionsByIndexRequest.toObject(includeInstance, f),
    byhash: (f = msg.getByhash()) && proto.iotexapi.GetActionByHashRequest.toObject(includeInstance, f),
    byaddr: (f = msg.getByaddr()) && proto.iotexapi.GetActionByHashRequest.toObject(includeInstance, f),
    unconfirmedbyaddr: (f = msg.getUnconfirmedbyaddr()) && proto.iotexapi.GetUnconfirmedActionsByAddressRequest.toObject(includeInstance, f),
    byblk: (f = msg.getByblk()) && proto.iotexapi.GetActionsByBlockRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iotexapi.GetActionsRequest}
 */
proto.iotexapi.GetActionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iotexapi.GetActionsRequest;
  return proto.iotexapi.GetActionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iotexapi.GetActionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iotexapi.GetActionsRequest}
 */
proto.iotexapi.GetActionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.iotexapi.GetActionsByIndexRequest;
      reader.readMessage(value,proto.iotexapi.GetActionsByIndexRequest.deserializeBinaryFromReader);
      msg.setByindex(value);
      break;
    case 2:
      var value = new proto.iotexapi.GetActionByHashRequest;
      reader.readMessage(value,proto.iotexapi.GetActionByHashRequest.deserializeBinaryFromReader);
      msg.setByhash(value);
      break;
    case 3:
      var value = new proto.iotexapi.GetActionByHashRequest;
      reader.readMessage(value,proto.iotexapi.GetActionByHashRequest.deserializeBinaryFromReader);
      msg.setByaddr(value);
      break;
    case 4:
      var value = new proto.iotexapi.GetUnconfirmedActionsByAddressRequest;
      reader.readMessage(value,proto.iotexapi.GetUnconfirmedActionsByAddressRequest.deserializeBinaryFromReader);
      msg.setUnconfirmedbyaddr(value);
      break;
    case 5:
      var value = new proto.iotexapi.GetActionsByBlockRequest;
      reader.readMessage(value,proto.iotexapi.GetActionsByBlockRequest.deserializeBinaryFromReader);
      msg.setByblk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iotexapi.GetActionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iotexapi.GetActionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iotexapi.GetActionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iotexapi.GetActionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getByindex();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.iotexapi.GetActionsByIndexRequest.serializeBinaryToWriter
    );
  }
  f = message.getByhash();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.iotexapi.GetActionByHashRequest.serializeBinaryToWriter
    );
  }
  f = message.getByaddr();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.iotexapi.GetActionByHashRequest.serializeBinaryToWriter
    );
  }
  f = message.getUnconfirmedbyaddr();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.iotexapi.GetUnconfirmedActionsByAddressRequest.serializeBinaryToWriter
    );
  }
  f = message.getByblk();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.iotexapi.GetActionsByBlockRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional GetActionsByIndexRequest byIndex = 1;
 * @return {?proto.iotexapi.GetActionsByIndexRequest}
 */
proto.iotexapi.GetActionsRequest.prototype.getByindex = function() {
  return /** @type{?proto.iotexapi.GetActionsByIndexRequest} */ (
    jspb.Message.getWrapperField(this, proto.iotexapi.GetActionsByIndexRequest, 1));
};


/** @param {?proto.iotexapi.GetActionsByIndexRequest|undefined} value */
proto.iotexapi.GetActionsRequest.prototype.setByindex = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.iotexapi.GetActionsRequest.oneofGroups_[0], value);
};


proto.iotexapi.GetActionsRequest.prototype.clearByindex = function() {
  this.setByindex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.iotexapi.GetActionsRequest.prototype.hasByindex = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GetActionByHashRequest byHash = 2;
 * @return {?proto.iotexapi.GetActionByHashRequest}
 */
proto.iotexapi.GetActionsRequest.prototype.getByhash = function() {
  return /** @type{?proto.iotexapi.GetActionByHashRequest} */ (
    jspb.Message.getWrapperField(this, proto.iotexapi.GetActionByHashRequest, 2));
};


/** @param {?proto.iotexapi.GetActionByHashRequest|undefined} value */
proto.iotexapi.GetActionsRequest.prototype.setByhash = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.iotexapi.GetActionsRequest.oneofGroups_[0], value);
};


proto.iotexapi.GetActionsRequest.prototype.clearByhash = function() {
  this.setByhash(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.iotexapi.GetActionsRequest.prototype.hasByhash = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GetActionByHashRequest byAddr = 3;
 * @return {?proto.iotexapi.GetActionByHashRequest}
 */
proto.iotexapi.GetActionsRequest.prototype.getByaddr = function() {
  return /** @type{?proto.iotexapi.GetActionByHashRequest} */ (
    jspb.Message.getWrapperField(this, proto.iotexapi.GetActionByHashRequest, 3));
};


/** @param {?proto.iotexapi.GetActionByHashRequest|undefined} value */
proto.iotexapi.GetActionsRequest.prototype.setByaddr = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.iotexapi.GetActionsRequest.oneofGroups_[0], value);
};


proto.iotexapi.GetActionsRequest.prototype.clearByaddr = function() {
  this.setByaddr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.iotexapi.GetActionsRequest.prototype.hasByaddr = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional GetUnconfirmedActionsByAddressRequest unconfirmedByAddr = 4;
 * @return {?proto.iotexapi.GetUnconfirmedActionsByAddressRequest}
 */
proto.iotexapi.GetActionsRequest.prototype.getUnconfirmedbyaddr = function() {
  return /** @type{?proto.iotexapi.GetUnconfirmedActionsByAddressRequest} */ (
    jspb.Message.getWrapperField(this, proto.iotexapi.GetUnconfirmedActionsByAddressRequest, 4));
};


/** @param {?proto.iotexapi.GetUnconfirmedActionsByAddressRequest|undefined} value */
proto.iotexapi.GetActionsRequest.prototype.setUnconfirmedbyaddr = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.iotexapi.GetActionsRequest.oneofGroups_[0], value);
};


proto.iotexapi.GetActionsRequest.prototype.clearUnconfirmedbyaddr = function() {
  this.setUnconfirmedbyaddr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.iotexapi.GetActionsRequest.prototype.hasUnconfirmedbyaddr = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GetActionsByBlockRequest byBlk = 5;
 * @return {?proto.iotexapi.GetActionsByBlockRequest}
 */
proto.iotexapi.GetActionsRequest.prototype.getByblk = function() {
  return /** @type{?proto.iotexapi.GetActionsByBlockRequest} */ (
    jspb.Message.getWrapperField(this, proto.iotexapi.GetActionsByBlockRequest, 5));
};


/** @param {?proto.iotexapi.GetActionsByBlockRequest|undefined} value */
proto.iotexapi.GetActionsRequest.prototype.setByblk = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.iotexapi.GetActionsRequest.oneofGroups_[0], value);
};


proto.iotexapi.GetActionsRequest.prototype.clearByblk = function() {
  this.setByblk(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.iotexapi.GetActionsRequest.prototype.hasByblk = function() {
  return jspb.Message.getField(this, 5) != null;
};


