/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.iproto.PlumChallengeExit');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.iproto.PlumChallengeExit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.iproto.PlumChallengeExit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.iproto.PlumChallengeExit.displayName = 'proto.iproto.PlumChallengeExit';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.iproto.PlumChallengeExit.prototype.toObject = function(opt_includeInstance) {
  return proto.iproto.PlumChallengeExit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.iproto.PlumChallengeExit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iproto.PlumChallengeExit.toObject = function(includeInstance, msg) {
  var f, obj = {
    subchainaddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    coinid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    challengetransfer: msg.getChallengetransfer_asB64(),
    challengetransferblockproof: msg.getChallengetransferblockproof_asB64(),
    challengetransferblockheight: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.iproto.PlumChallengeExit}
 */
proto.iproto.PlumChallengeExit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.iproto.PlumChallengeExit;
  return proto.iproto.PlumChallengeExit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.iproto.PlumChallengeExit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.iproto.PlumChallengeExit}
 */
proto.iproto.PlumChallengeExit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubchainaddress(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCoinid(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setChallengetransfer(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setChallengetransferblockproof(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setChallengetransferblockheight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.iproto.PlumChallengeExit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.iproto.PlumChallengeExit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.iproto.PlumChallengeExit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.iproto.PlumChallengeExit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSubchainaddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCoinid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getChallengetransfer_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getChallengetransferblockproof_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getChallengetransferblockheight();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
};


/**
 * optional string subChainAddress = 1;
 * @return {string}
 */
proto.iproto.PlumChallengeExit.prototype.getSubchainaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.iproto.PlumChallengeExit.prototype.setSubchainaddress = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 coinID = 2;
 * @return {number}
 */
proto.iproto.PlumChallengeExit.prototype.getCoinid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.iproto.PlumChallengeExit.prototype.setCoinid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bytes challengeTransfer = 3;
 * @return {string}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransfer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes challengeTransfer = 3;
 * This is a type-conversion wrapper around `getChallengetransfer()`
 * @return {string}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransfer_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getChallengetransfer()));
};


/**
 * optional bytes challengeTransfer = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getChallengetransfer()`
 * @return {!Uint8Array}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransfer_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getChallengetransfer()));
};


/** @param {!(string|Uint8Array)} value */
proto.iproto.PlumChallengeExit.prototype.setChallengetransfer = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes challengeTransferBlockProof = 4;
 * @return {string}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransferblockproof = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes challengeTransferBlockProof = 4;
 * This is a type-conversion wrapper around `getChallengetransferblockproof()`
 * @return {string}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransferblockproof_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getChallengetransferblockproof()));
};


/**
 * optional bytes challengeTransferBlockProof = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getChallengetransferblockproof()`
 * @return {!Uint8Array}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransferblockproof_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getChallengetransferblockproof()));
};


/** @param {!(string|Uint8Array)} value */
proto.iproto.PlumChallengeExit.prototype.setChallengetransferblockproof = function(value) {
  jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional uint64 challengeTransferBlockHeight = 5;
 * @return {number}
 */
proto.iproto.PlumChallengeExit.prototype.getChallengetransferblockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.iproto.PlumChallengeExit.prototype.setChallengetransferblockheight = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


