import * as jspb from "google-protobuf"

export enum ReceiptStatus { 
  Failure = 0,
  Success = 1,
  ErrUnknown = 100,
  ErrOutOfGas = 101,
  ErrCodeStoreOutOfGas = 102,
  ErrDepth = 103,
  ErrContractAddressCollision = 104,
  ErrNoCompatibleInterpreter = 105,
  ErrExecutionReverted = 106,
  ErrMaxCodeSizeExceeded = 107,
  ErrWriteProtection = 108,
  ErrLoadAccount = 200,
  ErrNotEnoughBalance = 201,
  ErrInvalidBucketIndex = 202,
  ErrUnauthorizedOperator = 203,
  ErrInvalidBucketType = 204,
  ErrCandidateNotExist = 205,
  ErrReduceDurationBeforeMaturity = 206,
  ErrUnstakeBeforeMaturity = 207,
  ErrWithdrawBeforeUnstake = 208,
  ErrWithdrawBeforeMaturity = 209,
  ErrCandidateAlreadyExist = 210,
  ErrCandidateConflict = 211,
}
